"""
Centralized Error Codes Constants
All error codes for the UC2 Core Service - imported from dn_errorcodes.md
Format: ERR.CORE.{MODULE}.{OPERATION}.{REASON}

Usage:
    from app.constants.error_codes import ErrorCodes
    error_code = ErrorCodes.UNIT_CREATE_FAILED
"""


class ErrorCodes:
    """
    Centralized error codes for all modules.
    All codes follow the pattern: ERR.CORE.{MODULE}.{OPERATION}.{REASON}
    """

    # =========================================================================
    # UNIT Error Codes
    # =========================================================================
    UNIT_CREATE_FAILED = "ERR.CORE.UNIT.CREATE.FAILED"
    UNIT_CREATE_INVALID_UNIT_TYPE = "ERR.CORE.UNIT.CREATE.INVALID_UNIT_TYPE"
    UNIT_CREATE_INVALID_PARENT = "ERR.CORE.UNIT.CREATE.INVALID_PARENT"
    UNIT_CREATE_INVALID_DEPARTMENT = "ERR.CORE.UNIT.CREATE.INVALID_DEPARTMENT"
    UNIT_CREATE_INVALID_DISTRICT = "ERR.CORE.UNIT.CREATE.INVALID_DISTRICT"
    UNIT_CREATE_INVALID_PROXY_USER = "ERR.CORE.UNIT.CREATE.INVALID_PROXY_USER"
    UNIT_CREATE_INVALID_RESPONSIBLE_USER = "ERR.CORE.UNIT.CREATE.INVALID_RESPONSIBLE_USER"
    UNIT_CREATE_DUPLICATE_REFERENCE = "ERR.CORE.UNIT.CREATE.DUPLICATE_REFERENCE"
    UNIT_UPDATE_NOT_FOUND = "ERR.CORE.UNIT.UPDATE.NOT_FOUND"
    UNIT_UPDATE_FAILED = "ERR.CORE.UNIT.UPDATE.FAILED"
    UNIT_UPDATE_CIRCULAR_HIERARCHY = "ERR.CORE.UNIT.UPDATE.CIRCULAR_HIERARCHY"
    UNIT_UPDATE_DUPLICATE_REFERENCE = "ERR.CORE.UNIT.UPDATE.DUPLICATE_REFERENCE"
    UNIT_DELETE_NOT_FOUND = "ERR.CORE.UNIT.DELETE.NOT_FOUND"
    UNIT_DELETE_FAILED = "ERR.CORE.UNIT.DELETE.FAILED"
    UNIT_DELETE_HAS_CHILDREN = "ERR.CORE.UNIT.DELETE.HAS_CHILDREN"
    UNIT_DELETE_HAS_CHILDREN_PATH = "ERR.CORE.UNIT.DELETE.HAS_CHILDREN_PATH"
    UNIT_DELETE_HAS_PERSONNEL = "ERR.CORE.UNIT.DELETE.HAS_PERSONNEL"
    UNIT_GET_NOT_FOUND = "ERR.CORE.UNIT.GET.NOT_FOUND"
    UNIT_LIST_FAILED = "ERR.CORE.UNIT.LIST.FAILED"
    UNIT_PARENT_NOT_FOUND = "ERR.CORE.UNIT.PARENT_NOT_FOUND"
    UNIT_PATH_CALCULATION_FAILED = "ERR.CORE.UNIT.PATH.CALCULATION_FAILED"
    UNIT_RESTORE_NOT_FOUND = "ERR.CORE.UNIT.RESTORE.NOT_FOUND"
    UNIT_RESTORE_FAILED = "ERR.CORE.UNIT.RESTORE.FAILED"

    # =========================================================================
    # UNIT_TYPE Error Codes
    # =========================================================================
    UNIT_TYPE_CREATE_FAILED = "ERR.CORE.UNIT_TYPE.CREATE.FAILED"
    UNIT_TYPE_CREATE_DUPLICATE_NAME = "ERR.CORE.UNIT_TYPE.CREATE.DUPLICATE_NAME"
    UNIT_TYPE_CREATE_INVALID_DEPARTMENT = "ERR.CORE.UNIT_TYPE.CREATE.INVALID_DEPARTMENT"
    UNIT_TYPE_UPDATE_NOT_FOUND = "ERR.CORE.UNIT_TYPE.UPDATE.NOT_FOUND"
    UNIT_TYPE_UPDATE_FAILED = "ERR.CORE.UNIT_TYPE.UPDATE.FAILED"
    UNIT_TYPE_UPDATE_DUPLICATE_NAME = "ERR.CORE.UNIT_TYPE.UPDATE.DUPLICATE_NAME"
    UNIT_TYPE_DELETE_NOT_FOUND = "ERR.CORE.UNIT_TYPE.DELETE.NOT_FOUND"
    UNIT_TYPE_DELETE_FAILED = "ERR.CORE.UNIT_TYPE.DELETE.FAILED"
    UNIT_TYPE_DELETE_IN_USE = "ERR.CORE.UNIT_TYPE.DELETE.IN_USE"
    UNIT_TYPE_DELETE_HAS_REFERENCES = "ERR.CORE.UNIT_TYPE.DELETE.HAS_REFERENCES"
    UNIT_TYPE_GET_NOT_FOUND = "ERR.CORE.UNIT_TYPE.GET.NOT_FOUND"
    UNIT_TYPE_LIST_FAILED = "ERR.CORE.UNIT_TYPE.LIST.FAILED"

    # =========================================================================
    # UNIT_VILLAGE Error Codes
    # =========================================================================
    UNIT_VILLAGE_CREATE_FAILED = "ERR.CORE.UNIT_VILLAGE.CREATE.FAILED"
    UNIT_VILLAGE_CREATE_INVALID_UNIT = "ERR.CORE.UNIT_VILLAGE.CREATE.INVALID_UNIT"
    UNIT_VILLAGE_CREATE_INVALID_VILLAGE = "ERR.CORE.UNIT_VILLAGE.CREATE.INVALID_VILLAGE"
    UNIT_VILLAGE_CREATE_DUPLICATE = "ERR.CORE.UNIT_VILLAGE.CREATE.DUPLICATE"
    UNIT_VILLAGE_UPDATE_NOT_FOUND = "ERR.CORE.UNIT_VILLAGE.UPDATE.NOT_FOUND"
    UNIT_VILLAGE_UPDATE_FAILED = "ERR.CORE.UNIT_VILLAGE.UPDATE.FAILED"
    UNIT_VILLAGE_DELETE_NOT_FOUND = "ERR.CORE.UNIT_VILLAGE.DELETE.NOT_FOUND"
    UNIT_VILLAGE_DELETE_FAILED = "ERR.CORE.UNIT_VILLAGE.DELETE.FAILED"
    UNIT_VILLAGE_GET_NOT_FOUND = "ERR.CORE.UNIT_VILLAGE.GET.NOT_FOUND"
    UNIT_VILLAGE_LIST_FAILED = "ERR.CORE.UNIT_VILLAGE.LIST.FAILED"

    # =========================================================================
    # ORG_STRUCTURE Error Codes
    # =========================================================================
    ORG_STRUCTURE_FETCH_FAILED = "ERR.CORE.ORG_STRUCTURE.FETCH.FAILED"
    ORG_STRUCTURE_INVALID_FORMAT = "ERR.CORE.ORG_STRUCTURE.INVALID_FORMAT"
    ORG_STRUCTURE_UNIT_NOT_FOUND = "ERR.CORE.ORG_STRUCTURE.UNIT_NOT_FOUND"

    # =========================================================================
    # PERSONNEL Error Codes
    # =========================================================================
    PERSONNEL_CREATE_FAILED = "ERR.CORE.PERSONNEL.CREATE.FAILED"
    PERSONNEL_CREATE_DUPLICATE_EMAIL = "ERR.CORE.PERSONNEL.CREATE.DUPLICATE_EMAIL"
    PERSONNEL_CREATE_INVALID_DEPARTMENT = "ERR.CORE.PERSONNEL.CREATE.INVALID_DEPARTMENT"
    PERSONNEL_CREATE_INVALID_RANK = "ERR.CORE.PERSONNEL.CREATE.INVALID_RANK"
    PERSONNEL_CREATE_INVALID_UNIT = "ERR.CORE.PERSONNEL.CREATE.INVALID_UNIT"
    PERSONNEL_CREATE_INVALID_DISTRICT = "ERR.CORE.PERSONNEL.CREATE.INVALID_DISTRICT"
    PERSONNEL_UPDATE_NOT_FOUND = "ERR.CORE.PERSONNEL.UPDATE.NOT_FOUND"
    PERSONNEL_UPDATE_FAILED = "ERR.CORE.PERSONNEL.UPDATE.FAILED"
    PERSONNEL_UPDATE_DUPLICATE_EMAIL = "ERR.CORE.PERSONNEL.UPDATE.DUPLICATE_EMAIL"
    PERSONNEL_DELETE_NOT_FOUND = "ERR.CORE.PERSONNEL.DELETE.NOT_FOUND"
    PERSONNEL_DELETE_FAILED = "ERR.CORE.PERSONNEL.DELETE.FAILED"
    PERSONNEL_DELETE_IS_PROXY_USER = "ERR.CORE.PERSONNEL.DELETE.IS_PROXY_USER"
    PERSONNEL_DELETE_IS_RESPONSIBLE_USER = "ERR.CORE.PERSONNEL.DELETE.IS_RESPONSIBLE_USER"
    PERSONNEL_GET_NOT_FOUND = "ERR.CORE.PERSONNEL.GET.NOT_FOUND"
    PERSONNEL_LIST_FAILED = "ERR.CORE.PERSONNEL.LIST.FAILED"
    PERSONNEL_USERID_EXISTS = "ERR.CORE.PERSONNEL.USERID_EXISTS"
    PERSONNEL_AUTH_ACCOUNT_LOCKED = "ERR.CORE.PERSONNEL.AUTH.ACCOUNT_LOCKED"
    PERSONNEL_AUTH_INVALID_CREDENTIALS = "ERR.CORE.PERSONNEL.AUTH.INVALID_CREDENTIALS"
    PERSONNEL_PASSWORD_HASH_FAILED = "ERR.CORE.PERSONNEL.PASSWORD.HASH_FAILED"

    # =========================================================================
    # DEPARTMENT Error Codes
    # =========================================================================
    DEPARTMENT_CREATE_FAILED = "ERR.CORE.DEPARTMENT.CREATE.FAILED"
    DEPARTMENT_CREATE_DUPLICATE_NAME = "ERR.CORE.DEPARTMENT.CREATE.DUPLICATE_NAME"
    DEPARTMENT_CREATE_DUPLICATE_CCTNS_CODE = "ERR.CORE.DEPARTMENT.CREATE.DUPLICATE_CCTNS_CODE"
    DEPARTMENT_UPDATE_NOT_FOUND = "ERR.CORE.DEPARTMENT.UPDATE.NOT_FOUND"
    DEPARTMENT_UPDATE_FAILED = "ERR.CORE.DEPARTMENT.UPDATE.FAILED"
    DEPARTMENT_UPDATE_DUPLICATE_NAME = "ERR.CORE.DEPARTMENT.UPDATE.DUPLICATE_NAME"
    DEPARTMENT_UPDATE_DUPLICATE_CCTNS_CODE = "ERR.CORE.DEPARTMENT.UPDATE.DUPLICATE_CCTNS_CODE"
    DEPARTMENT_DELETE_NOT_FOUND = "ERR.CORE.DEPARTMENT.DELETE.NOT_FOUND"
    DEPARTMENT_DELETE_FAILED = "ERR.CORE.DEPARTMENT.DELETE.FAILED"
    DEPARTMENT_DELETE_IN_USE = "ERR.CORE.DEPARTMENT.DELETE.IN_USE"
    DEPARTMENT_DELETE_HAS_PERSONNEL = "ERR.CORE.DEPARTMENT.DELETE.HAS_PERSONNEL"
    DEPARTMENT_DELETE_HAS_REFERENCES = "ERR.CORE.DEPARTMENT.DELETE.HAS_REFERENCES"
    DEPARTMENT_GET_NOT_FOUND = "ERR.CORE.DEPARTMENT.GET.NOT_FOUND"
    DEPARTMENT_LIST_FAILED = "ERR.CORE.DEPARTMENT.LIST.FAILED"

    # =========================================================================
    # DISTRICT Error Codes
    # =========================================================================
    DISTRICT_CREATE_FAILED = "ERR.CORE.DISTRICT.CREATE.FAILED"
    DISTRICT_CREATE_DUPLICATE_NAME = "ERR.CORE.DISTRICT.CREATE.DUPLICATE_NAME"
    DISTRICT_CREATE_DUPLICATE_CCTNS_CODE = "ERR.CORE.DISTRICT.CREATE.DUPLICATE_CCTNS_CODE"
    DISTRICT_UPDATE_NOT_FOUND = "ERR.CORE.DISTRICT.UPDATE.NOT_FOUND"
    DISTRICT_UPDATE_FAILED = "ERR.CORE.DISTRICT.UPDATE.FAILED"
    DISTRICT_UPDATE_DUPLICATE_CCTNS_CODE = "ERR.CORE.DISTRICT.UPDATE.DUPLICATE_CCTNS_CODE"
    DISTRICT_DELETE_NOT_FOUND = "ERR.CORE.DISTRICT.DELETE.NOT_FOUND"
    DISTRICT_DELETE_FAILED = "ERR.CORE.DISTRICT.DELETE.FAILED"
    DISTRICT_DELETE_IN_USE = "ERR.CORE.DISTRICT.DELETE.IN_USE"
    DISTRICT_GET_NOT_FOUND = "ERR.CORE.DISTRICT.GET.NOT_FOUND"
    DISTRICT_LIST_FAILED = "ERR.CORE.DISTRICT.LIST.FAILED"

    # =========================================================================
    # MANDAL Error Codes
    # =========================================================================
    MANDAL_CREATE_FAILED = "ERR.CORE.MANDAL.CREATE.FAILED"
    MANDAL_CREATE_INVALID_DISTRICT = "ERR.CORE.MANDAL.CREATE.INVALID_DISTRICT"
    MANDAL_CREATE_DUPLICATE_NAME = "ERR.CORE.MANDAL.CREATE.DUPLICATE_NAME"
    MANDAL_UPDATE_NOT_FOUND = "ERR.CORE.MANDAL.UPDATE.NOT_FOUND"
    MANDAL_UPDATE_FAILED = "ERR.CORE.MANDAL.UPDATE.FAILED"
    MANDAL_UPDATE_DUPLICATE_NAME = "ERR.CORE.MANDAL.UPDATE.DUPLICATE_NAME"
    MANDAL_DELETE_NOT_FOUND = "ERR.CORE.MANDAL.DELETE.NOT_FOUND"
    MANDAL_DELETE_FAILED = "ERR.CORE.MANDAL.DELETE.FAILED"
    MANDAL_DELETE_IN_USE = "ERR.CORE.MANDAL.DELETE.IN_USE"
    MANDAL_GET_NOT_FOUND = "ERR.CORE.MANDAL.GET.NOT_FOUND"
    MANDAL_LIST_FAILED = "ERR.CORE.MANDAL.LIST.FAILED"

    # =========================================================================
    # RANK Error Codes
    # =========================================================================
    RANK_CREATE_FAILED = "ERR.CORE.RANK.CREATE.FAILED"
    RANK_CREATE_DUPLICATE_NAME = "ERR.CORE.RANK.CREATE.DUPLICATE_NAME"
    RANK_CREATE_DUPLICATE_SEQUENCE = "ERR.CORE.RANK.CREATE.DUPLICATE_SEQUENCE"
    RANK_UPDATE_NOT_FOUND = "ERR.CORE.RANK.UPDATE.NOT_FOUND"
    RANK_UPDATE_FAILED = "ERR.CORE.RANK.UPDATE.FAILED"
    RANK_UPDATE_DUPLICATE_NAME = "ERR.CORE.RANK.UPDATE.DUPLICATE_NAME"
    RANK_UPDATE_DUPLICATE_SEQUENCE = "ERR.CORE.RANK.UPDATE.DUPLICATE_SEQUENCE"
    RANK_DELETE_NOT_FOUND = "ERR.CORE.RANK.DELETE.NOT_FOUND"
    RANK_DELETE_FAILED = "ERR.CORE.RANK.DELETE.FAILED"
    RANK_DELETE_IN_USE = "ERR.CORE.RANK.DELETE.IN_USE"
    RANK_GET_NOT_FOUND = "ERR.CORE.RANK.GET.NOT_FOUND"
    RANK_LIST_FAILED = "ERR.CORE.RANK.LIST.FAILED"

    # =========================================================================
    # VALUESET Error Codes
    # =========================================================================
    VALUESET_CREATE_FAILED = "ERR.CORE.VALUESET.CREATE.FAILED"
    VALUESET_CREATE_DUPLICATE_KEY = "ERR.CORE.VALUESET.CREATE.DUPLICATE_KEY"
    VALUESET_CREATE_DUPLICATE_ITEM_CODE = "ERR.CORE.VALUESET.CREATE.DUPLICATE_ITEM_CODE"
    VALUESET_CREATE_DUPLICATE_LABEL = "ERR.CORE.VALUESET.CREATE.DUPLICATE_LABEL"
    VALUESET_UPDATE_NOT_FOUND = "ERR.CORE.VALUESET.UPDATE.NOT_FOUND"
    VALUESET_UPDATE_FAILED = "ERR.CORE.VALUESET.UPDATE.FAILED"
    VALUESET_UPDATE_DUPLICATE_ITEM_CODE = "ERR.CORE.VALUESET.UPDATE.DUPLICATE_ITEM_CODE"
    VALUESET_GET_NOT_FOUND = "ERR.CORE.VALUESET.GET.NOT_FOUND"
    VALUESET_LIST_FAILED = "ERR.CORE.VALUESET.LIST.FAILED"
    VALUESET_VALIDATE_NOT_FOUND = "ERR.CORE.VALUESET.VALIDATE.NOT_FOUND"
    VALUESET_VALIDATE_ARCHIVED = "ERR.CORE.VALUESET.VALIDATE.ARCHIVED"
    VALUESET_ARCHIVE_NOT_FOUND = "ERR.CORE.VALUESET.ARCHIVE.NOT_FOUND"
    VALUESET_ARCHIVE_FAILED = "ERR.CORE.VALUESET.ARCHIVE.FAILED"
    VALUESET_CACHE_REFRESH_FAILED = "ERR.CORE.VALUESET.CACHE.REFRESH_FAILED"
    VALUESET_BOOTSTRAP_FAILED = "ERR.CORE.VALUESET.BOOTSTRAP.FAILED"

    # =========================================================================
    # MODULE Error Codes
    # =========================================================================
    MODULE_CREATE_FAILED = "ERR.CORE.MODULE.CREATE.FAILED"
    MODULE_CREATE_DUPLICATE_NAME = "ERR.CORE.MODULE.CREATE.DUPLICATE_NAME"
    MODULE_CREATE_DUPLICATE_SHORT_CODE = "ERR.CORE.MODULE.CREATE.DUPLICATE_SHORT_CODE"
    MODULE_UPDATE_NOT_FOUND = "ERR.CORE.MODULE.UPDATE.NOT_FOUND"
    MODULE_UPDATE_FAILED = "ERR.CORE.MODULE.UPDATE.FAILED"
    MODULE_UPDATE_DUPLICATE_NAME = "ERR.CORE.MODULE.UPDATE.DUPLICATE_NAME"
    MODULE_UPDATE_DUPLICATE_SHORT_CODE = "ERR.CORE.MODULE.UPDATE.DUPLICATE_SHORT_CODE"
    MODULE_DELETE_NOT_FOUND = "ERR.CORE.MODULE.DELETE.NOT_FOUND"
    MODULE_DELETE_FAILED = "ERR.CORE.MODULE.DELETE.FAILED"
    MODULE_DELETE_IN_USE = "ERR.CORE.MODULE.DELETE.IN_USE"
    MODULE_DELETE_HAS_HIERARCHY = "ERR.CORE.MODULE.DELETE.HAS_HIERARCHY"
    MODULE_RESTORE_NOT_FOUND = "ERR.CORE.MODULE.RESTORE.NOT_FOUND"
    MODULE_RESTORE_FAILED = "ERR.CORE.MODULE.RESTORE.FAILED"
    MODULE_RESTORE_ALREADY_ACTIVE = "ERR.CORE.MODULE.RESTORE.ALREADY_ACTIVE"
    MODULE_TOGGLE_NOT_FOUND = "ERR.CORE.MODULE.TOGGLE.NOT_FOUND"
    MODULE_TOGGLE_FAILED = "ERR.CORE.MODULE.TOGGLE.FAILED"
    MODULE_GET_NOT_FOUND = "ERR.CORE.MODULE.GET.NOT_FOUND"
    MODULE_LIST_FAILED = "ERR.CORE.MODULE.LIST.FAILED"
    MODULE_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.MODULE.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # MODULE_HIERARCHY Error Codes
    # =========================================================================
    MOD_HIERARCHY_CREATE_FAILED = "ERR.CORE.MOD_HIERARCHY.CREATE.FAILED"
    MOD_HIERARCHY_CREATE_DUPLICATE = "ERR.CORE.MOD_HIERARCHY.CREATE.DUPLICATE"
    MOD_HIERARCHY_CREATE_INVALID_PARENT = "ERR.CORE.MOD_HIERARCHY.CREATE.INVALID_PARENT"
    MOD_HIERARCHY_CREATE_INVALID_CHILD = "ERR.CORE.MOD_HIERARCHY.CREATE.INVALID_CHILD"
    MOD_HIERARCHY_CREATE_SELF_REFERENCE = "ERR.CORE.MOD_HIERARCHY.CREATE.SELF_REFERENCE"
    MOD_HIERARCHY_CREATE_CIRCULAR = "ERR.CORE.MOD_HIERARCHY.CREATE.CIRCULAR"
    MOD_HIERARCHY_UPDATE_NOT_FOUND = "ERR.CORE.MOD_HIERARCHY.UPDATE.NOT_FOUND"
    MOD_HIERARCHY_UPDATE_FAILED = "ERR.CORE.MOD_HIERARCHY.UPDATE.FAILED"
    MOD_HIERARCHY_UPDATE_CIRCULAR = "ERR.CORE.MOD_HIERARCHY.UPDATE.CIRCULAR"
    MOD_HIERARCHY_DELETE_NOT_FOUND = "ERR.CORE.MOD_HIERARCHY.DELETE.NOT_FOUND"
    MOD_HIERARCHY_DELETE_FAILED = "ERR.CORE.MOD_HIERARCHY.DELETE.FAILED"
    MOD_HIERARCHY_GET_NOT_FOUND = "ERR.CORE.MOD_HIERARCHY.GET.NOT_FOUND"
    MOD_HIERARCHY_LIST_FAILED = "ERR.CORE.MOD_HIERARCHY.LIST.FAILED"
    MOD_HIERARCHY_TREE_BUILD_FAILED = "ERR.CORE.MOD_HIERARCHY.TREE.BUILD_FAILED"

    # =========================================================================
    # JOB Error Codes
    # =========================================================================
    JOB_CREATE_FAILED = "ERR.CORE.JOB.CREATE.FAILED"
    JOB_CREATE_DUPLICATE_NAME = "ERR.CORE.JOB.CREATE.DUPLICATE_NAME"
    JOB_CREATE_DUPLICATE_SHORT_CODE = "ERR.CORE.JOB.CREATE.DUPLICATE_SHORT_CODE"
    JOB_UPDATE_NOT_FOUND = "ERR.CORE.JOB.UPDATE.NOT_FOUND"
    JOB_UPDATE_FAILED = "ERR.CORE.JOB.UPDATE.FAILED"
    JOB_UPDATE_DUPLICATE_NAME = "ERR.CORE.JOB.UPDATE.DUPLICATE_NAME"
    JOB_UPDATE_DUPLICATE_SHORT_CODE = "ERR.CORE.JOB.UPDATE.DUPLICATE_SHORT_CODE"
    JOB_DELETE_NOT_FOUND = "ERR.CORE.JOB.DELETE.NOT_FOUND"
    JOB_DELETE_FAILED = "ERR.CORE.JOB.DELETE.FAILED"
    JOB_DELETE_IN_USE = "ERR.CORE.JOB.DELETE.IN_USE"
    JOB_GET_NOT_FOUND = "ERR.CORE.JOB.GET.NOT_FOUND"
    JOB_LIST_FAILED = "ERR.CORE.JOB.LIST.FAILED"
    JOB_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.JOB.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # ROLE Error Codes
    # =========================================================================
    ROLE_CREATE_FAILED = "ERR.CORE.ROLE.CREATE.FAILED"
    ROLE_CREATE_DUPLICATE_NAME = "ERR.CORE.ROLE.CREATE.DUPLICATE_NAME"
    ROLE_CREATE_DUPLICATE_SHORT_CODE = "ERR.CORE.ROLE.CREATE.DUPLICATE_SHORT_CODE"
    ROLE_CREATE_INVALID_JOB = "ERR.CORE.ROLE.CREATE.INVALID_JOB"
    ROLE_CREATE_INVALID_MODULE = "ERR.CORE.ROLE.CREATE.INVALID_MODULE"
    ROLE_CREATE_INVALID_PERMISSION = "ERR.CORE.ROLE.CREATE.INVALID_PERMISSION"
    ROLE_UPDATE_NOT_FOUND = "ERR.CORE.ROLE.UPDATE.NOT_FOUND"
    ROLE_UPDATE_FAILED = "ERR.CORE.ROLE.UPDATE.FAILED"
    ROLE_UPDATE_DUPLICATE_NAME = "ERR.CORE.ROLE.UPDATE.DUPLICATE_NAME"
    ROLE_UPDATE_DUPLICATE_SHORT_CODE = "ERR.CORE.ROLE.UPDATE.DUPLICATE_SHORT_CODE"
    ROLE_DELETE_NOT_FOUND = "ERR.CORE.ROLE.DELETE.NOT_FOUND"
    ROLE_DELETE_FAILED = "ERR.CORE.ROLE.DELETE.FAILED"
    ROLE_DELETE_IN_USE = "ERR.CORE.ROLE.DELETE.IN_USE"
    ROLE_GET_NOT_FOUND = "ERR.CORE.ROLE.GET.NOT_FOUND"
    ROLE_LIST_FAILED = "ERR.CORE.ROLE.LIST.FAILED"

    # =========================================================================
    # PERMISSION Error Codes
    # =========================================================================
    PERMISSION_CREATE_FAILED = "ERR.CORE.PERMISSION.CREATE.FAILED"
    PERMISSION_CREATE_DUPLICATE_NAME = "ERR.CORE.PERMISSION.CREATE.DUPLICATE_NAME"
    PERMISSION_CREATE_DUPLICATE_SHORT_CODE = "ERR.CORE.PERMISSION.CREATE.DUPLICATE_SHORT_CODE"
    PERMISSION_UPDATE_NOT_FOUND = "ERR.CORE.PERMISSION.UPDATE.NOT_FOUND"
    PERMISSION_UPDATE_FAILED = "ERR.CORE.PERMISSION.UPDATE.FAILED"
    PERMISSION_UPDATE_DUPLICATE_NAME = "ERR.CORE.PERMISSION.UPDATE.DUPLICATE_NAME"
    PERMISSION_UPDATE_DUPLICATE_SHORT_CODE = "ERR.CORE.PERMISSION.UPDATE.DUPLICATE_SHORT_CODE"
    PERMISSION_DELETE_NOT_FOUND = "ERR.CORE.PERMISSION.DELETE.NOT_FOUND"
    PERMISSION_DELETE_FAILED = "ERR.CORE.PERMISSION.DELETE.FAILED"
    PERMISSION_DELETE_IN_USE = "ERR.CORE.PERMISSION.DELETE.IN_USE"
    PERMISSION_GET_NOT_FOUND = "ERR.CORE.PERMISSION.GET.NOT_FOUND"
    PERMISSION_LIST_FAILED = "ERR.CORE.PERMISSION.LIST.FAILED"
    PERMISSION_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.PERMISSION.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # PERMISSION_MAPPING Error Codes
    # =========================================================================
    PERM_MAPPING_CREATE_FAILED = "ERR.CORE.PERM_MAPPING.CREATE.FAILED"
    PERM_MAPPING_CREATE_DUPLICATE = "ERR.CORE.PERM_MAPPING.CREATE.DUPLICATE"
    PERM_MAPPING_CREATE_INVALID_JOB = "ERR.CORE.PERM_MAPPING.CREATE.INVALID_JOB"
    PERM_MAPPING_CREATE_INVALID_MODULE = "ERR.CORE.PERM_MAPPING.CREATE.INVALID_MODULE"
    PERM_MAPPING_CREATE_INVALID_PERMISSION = "ERR.CORE.PERM_MAPPING.CREATE.INVALID_PERMISSION"
    PERM_MAPPING_UPDATE_NOT_FOUND = "ERR.CORE.PERM_MAPPING.UPDATE.NOT_FOUND"
    PERM_MAPPING_UPDATE_FAILED = "ERR.CORE.PERM_MAPPING.UPDATE.FAILED"
    PERM_MAPPING_UPDATE_DUPLICATE = "ERR.CORE.PERM_MAPPING.UPDATE.DUPLICATE"
    PERM_MAPPING_DELETE_NOT_FOUND = "ERR.CORE.PERM_MAPPING.DELETE.NOT_FOUND"
    PERM_MAPPING_DELETE_FAILED = "ERR.CORE.PERM_MAPPING.DELETE.FAILED"
    PERM_MAPPING_DELETE_IN_USE = "ERR.CORE.PERM_MAPPING.DELETE.IN_USE"
    PERM_MAPPING_RESTORE_NOT_FOUND = "ERR.CORE.PERM_MAPPING.RESTORE.NOT_FOUND"
    PERM_MAPPING_RESTORE_FAILED = "ERR.CORE.PERM_MAPPING.RESTORE.FAILED"
    PERM_MAPPING_GET_NOT_FOUND = "ERR.CORE.PERM_MAPPING.GET.NOT_FOUND"
    PERM_MAPPING_LIST_FAILED = "ERR.CORE.PERM_MAPPING.LIST.FAILED"
    PERM_MAPPING_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.PERM_MAPPING.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # MODULE_JOB_MAPPING Error Codes
    # =========================================================================
    MOD_JOB_MAPPING_CREATE_FAILED = "ERR.CORE.MOD_JOB_MAPPING.CREATE.FAILED"
    MOD_JOB_MAPPING_CREATE_DUPLICATE = "ERR.CORE.MOD_JOB_MAPPING.CREATE.DUPLICATE"
    MOD_JOB_MAPPING_CREATE_INVALID_JOB = "ERR.CORE.MOD_JOB_MAPPING.CREATE.INVALID_JOB"
    MOD_JOB_MAPPING_CREATE_INVALID_MODULE = "ERR.CORE.MOD_JOB_MAPPING.CREATE.INVALID_MODULE"
    MOD_JOB_MAPPING_UPDATE_NOT_FOUND = "ERR.CORE.MOD_JOB_MAPPING.UPDATE.NOT_FOUND"
    MOD_JOB_MAPPING_UPDATE_FAILED = "ERR.CORE.MOD_JOB_MAPPING.UPDATE.FAILED"
    MOD_JOB_MAPPING_UPDATE_DUPLICATE = "ERR.CORE.MOD_JOB_MAPPING.UPDATE.DUPLICATE"
    MOD_JOB_MAPPING_DELETE_NOT_FOUND = "ERR.CORE.MOD_JOB_MAPPING.DELETE.NOT_FOUND"
    MOD_JOB_MAPPING_DELETE_FAILED = "ERR.CORE.MOD_JOB_MAPPING.DELETE.FAILED"
    MOD_JOB_MAPPING_DELETE_IN_USE = "ERR.CORE.MOD_JOB_MAPPING.DELETE.IN_USE"
    MOD_JOB_MAPPING_RESTORE_NOT_FOUND = "ERR.CORE.MOD_JOB_MAPPING.RESTORE.NOT_FOUND"
    MOD_JOB_MAPPING_RESTORE_FAILED = "ERR.CORE.MOD_JOB_MAPPING.RESTORE.FAILED"
    MOD_JOB_MAPPING_GET_NOT_FOUND = "ERR.CORE.MOD_JOB_MAPPING.GET.NOT_FOUND"
    MOD_JOB_MAPPING_LIST_FAILED = "ERR.CORE.MOD_JOB_MAPPING.LIST.FAILED"
    MOD_JOB_MAPPING_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.MOD_JOB_MAPPING.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # USER_MAPPING Error Codes
    # =========================================================================
    USER_MAPPING_CREATE_FAILED = "ERR.CORE.USER_MAPPING.CREATE.FAILED"
    USER_MAPPING_CREATE_DUPLICATE = "ERR.CORE.USER_MAPPING.CREATE.DUPLICATE"
    USER_MAPPING_CREATE_INVALID_USER = "ERR.CORE.USER_MAPPING.CREATE.INVALID_USER"
    USER_MAPPING_CREATE_INVALID_ROLE = "ERR.CORE.USER_MAPPING.CREATE.INVALID_ROLE"
    USER_MAPPING_CREATE_INVALID_UNIT = "ERR.CORE.USER_MAPPING.CREATE.INVALID_UNIT"
    USER_MAPPING_CREATE_USER_NO_UNIT = "ERR.CORE.USER_MAPPING.CREATE.USER_NO_UNIT"
    USER_MAPPING_CREATE_USER_NO_RANK = "ERR.CORE.USER_MAPPING.CREATE.USER_NO_RANK"
    USER_MAPPING_CREATE_INVALID_ADD_MODULE = "ERR.CORE.USER_MAPPING.CREATE.INVALID_ADD_MODULE"
    USER_MAPPING_CREATE_INVALID_ADD_JOB = "ERR.CORE.USER_MAPPING.CREATE.INVALID_ADD_JOB"
    USER_MAPPING_CREATE_INVALID_ADD_PERMISSION = "ERR.CORE.USER_MAPPING.CREATE.INVALID_ADD_PERMISSION"
    USER_MAPPING_CREATE_INVALID_EXCL_PERMISSION = "ERR.CORE.USER_MAPPING.CREATE.INVALID_EXCL_PERMISSION"
    USER_MAPPING_UPDATE_NOT_FOUND = "ERR.CORE.USER_MAPPING.UPDATE.NOT_FOUND"
    USER_MAPPING_UPDATE_FAILED = "ERR.CORE.USER_MAPPING.UPDATE.FAILED"
    USER_MAPPING_UPDATE_DUPLICATE = "ERR.CORE.USER_MAPPING.UPDATE.DUPLICATE"
    USER_MAPPING_DELETE_NOT_FOUND = "ERR.CORE.USER_MAPPING.DELETE.NOT_FOUND"
    USER_MAPPING_DELETE_FAILED = "ERR.CORE.USER_MAPPING.DELETE.FAILED"
    USER_MAPPING_DELETE_ONLY_ROLE = "ERR.CORE.USER_MAPPING.DELETE.ONLY_ROLE"
    USER_MAPPING_GET_NOT_FOUND = "ERR.CORE.USER_MAPPING.GET.NOT_FOUND"
    USER_MAPPING_LIST_FAILED = "ERR.CORE.USER_MAPPING.LIST.FAILED"
    USER_MAPPING_CONSOLIDATE_FAILED = "ERR.CORE.USER_MAPPING.CONSOLIDATE.FAILED"

    # =========================================================================
    # AUTH Error Codes
    # =========================================================================
    AUTH_LOGIN_FAILED = "ERR.CORE.AUTH.LOGIN.FAILED"
    AUTH_TOKEN_MISSING = "ERR.CORE.AUTH.TOKEN_MISSING"
    AUTH_TOKEN_INVALID = "ERR.CORE.AUTH.TOKEN_INVALID"
    AUTH_INVALID_TOKEN = "ERR.CORE.AUTH.INVALID_TOKEN"
    AUTH_PERMISSION_DENIED = "ERR.CORE.AUTH.PERMISSION_DENIED"
    AUTH_USER_NOT_FOUND = "ERR.CORE.AUTH.USER_NOT_FOUND"
    AUTH_USER_DELETED = "ERR.CORE.AUTH.USER_DELETED"
    AUTH_INVALID_CREDENTIALS = "ERR.CORE.AUTH.INVALID_CREDENTIALS"
    AUTH_INVALID_USER_ID = "ERR.CORE.AUTH.INVALID_USER_ID"
    AUTH_MISSING_REQUIRED_FIELDS = "ERR.CORE.AUTH.MISSING_REQUIRED_FIELDS"
    AUTH_PASSWORD_REQUIRED = "ERR.CORE.AUTH.PASSWORD_REQUIRED"
    AUTH_PASSWORD_MIN_LENGTH = "ERR.CORE.AUTH.PASSWORD_MIN_LENGTH"
    AUTH_USER_ID_INVALID_FORMAT = "ERR.CORE.AUTH.USER_ID_INVALID_FORMAT"
    AUTH_USER_ID_TOO_LONG = "ERR.CORE.AUTH.USER_ID_TOO_LONG"
    AUTH_USER_ID_INVALID_CHARACTERS = "ERR.CORE.AUTH.USER_ID_INVALID_CHARACTERS"
    AUTH_IDENTIFIER_REQUIRED = "ERR.CORE.AUTH.IDENTIFIER_REQUIRED"
    AUTH_MPIN_REQUIRED = "ERR.CORE.AUTH.MPIN_REQUIRED"
    AUTH_MPIN_INVALID_FORMAT = "ERR.CORE.AUTH.MPIN_INVALID_FORMAT"
    AUTH_PHONE_INVALID_FORMAT = "ERR.CORE.AUTH.PHONE_INVALID_FORMAT"
    AUTH_INVALID_MPIN = "ERR.CORE.AUTH.INVALID_MPIN"
    AUTH_MISSING_UNIT_ID = "ERR.CORE.AUTH.MISSING_UNIT_ID"
    AUTH_MISSING_ROLE_ID = "ERR.CORE.AUTH.MISSING_ROLE_ID"
    AUTH_ACCESS_DENIED = "ERR.CORE.AUTH.ACCESS_DENIED"
    AUTH_INCOMPLETE_TOKEN = "ERR.CORE.AUTH.INCOMPLETE_TOKEN"
    AUTH_ROLE_NOT_FOUND = "ERR.CORE.AUTH.ROLE_NOT_FOUND"
    AUTH_ME_FAILED = "ERR.CORE.AUTH.ME.FAILED"
    AUTH_GET_PERMISSIONS_FAILED = "ERR.CORE.AUTH.GET_PERMISSIONS.FAILED"
    PERMISSION_ADMIN_REQUIRED = "ERR.CORE.PERMISSION.ADMIN_REQUIRED"
    USER_NOT_FOUND = "ERR.CORE.USER.NOT_FOUND"

    # =========================================================================
    # OTP Error Codes
    # =========================================================================
    OTP_SEND_FAILED = "ERR.CORE.OTP.SEND.FAILED"
    OTP_REQUIRED = "ERR.CORE.OTP.REQUIRED"
    OTP_INVALID = "ERR.CORE.OTP.INVALID"
    OTP_EXPIRED = "ERR.CORE.OTP.EXPIRED"
    OTP_ALREADY_USED = "ERR.CORE.OTP.ALREADY_USED"
    OTP_NOT_FOUND = "ERR.CORE.OTP.NOT_FOUND"
    OTP_VERIFY_FAILED = "ERR.CORE.OTP.VERIFY.FAILED"
    OTP_SESSION_REQUIRED = "ERR.CORE.OTP.SESSION_REQUIRED"
    OTP_SESSION_INVALID = "ERR.CORE.OTP.SESSION_INVALID"
    OTP_SESSION_EXPIRED = "ERR.CORE.OTP.SESSION_EXPIRED"
    MPIN_UPDATE_FAILED = "ERR.CORE.MPIN.UPDATE.FAILED"
    MPIN_SAME_AS_OLD = "ERR.CORE.MPIN.SAME_AS_OLD"
    USER_MOBILE_NOT_FOUND = "ERR.CORE.USER.MOBILE_NOT_FOUND"

    # =========================================================================
    # REFRESH TOKEN Error Codes
    # =========================================================================
    REFRESH_TOKEN_REQUIRED = "ERR.CORE.REFRESH_TOKEN.REQUIRED"
    REFRESH_TOKEN_INVALID = "ERR.CORE.REFRESH_TOKEN.INVALID"
    REFRESH_TOKEN_EXPIRED = "ERR.CORE.REFRESH_TOKEN.EXPIRED"
    REFRESH_TOKEN_REVOKED = "ERR.CORE.REFRESH_TOKEN.REVOKED"
    REFRESH_TOKEN_REUSED = "ERR.CORE.REFRESH_TOKEN.REUSED"
    REFRESH_TOKEN_NOT_FOUND = "ERR.CORE.REFRESH_TOKEN.NOT_FOUND"
    REFRESH_TOKEN_FAILED = "ERR.CORE.REFRESH_TOKEN.FAILED"
    LOGOUT_FAILED = "ERR.CORE.AUTH.LOGOUT.FAILED"
    SESSION_NOT_FOUND = "ERR.CORE.SESSION.NOT_FOUND"
    SESSION_REVOKE_FAILED = "ERR.CORE.SESSION.REVOKE.FAILED"
    MAX_SESSIONS_EXCEEDED = "ERR.CORE.SESSION.MAX_EXCEEDED"

    # =========================================================================
    # NOTIFICATION_MASTER Error Codes
    # =========================================================================
    NOTIF_MASTER_CREATE_FAILED = "ERR.CORE.NOTIF_MASTER.CREATE.FAILED"
    NOTIF_MASTER_CREATE_DUPLICATE_TYPE = "ERR.CORE.NOTIF_MASTER.CREATE.DUPLICATE_TYPE"
    NOTIF_MASTER_UPDATE_NOT_FOUND = "ERR.CORE.NOTIF_MASTER.UPDATE.NOT_FOUND"
    NOTIF_MASTER_UPDATE_FAILED = "ERR.CORE.NOTIF_MASTER.UPDATE.FAILED"
    NOTIF_MASTER_UPDATE_DUPLICATE_TYPE = "ERR.CORE.NOTIF_MASTER.UPDATE.DUPLICATE_TYPE"
    NOTIF_MASTER_DELETE_NOT_FOUND = "ERR.CORE.NOTIF_MASTER.DELETE.NOT_FOUND"
    NOTIF_MASTER_DELETE_FAILED = "ERR.CORE.NOTIF_MASTER.DELETE.FAILED"
    NOTIF_MASTER_DELETE_IN_USE = "ERR.CORE.NOTIF_MASTER.DELETE.IN_USE"
    NOTIF_MASTER_GET_NOT_FOUND = "ERR.CORE.NOTIF_MASTER.GET.NOT_FOUND"
    NOTIF_MASTER_GET_TYPE_NOT_FOUND = "ERR.CORE.NOTIF_MASTER.GET.TYPE_NOT_FOUND"
    NOTIF_MASTER_LIST_FAILED = "ERR.CORE.NOTIF_MASTER.LIST.FAILED"

    # =========================================================================
    # NOTIFICATION Error Codes
    # =========================================================================
    NOTIFICATION_CREATE_FAILED = "ERR.CORE.NOTIFICATION.CREATE.FAILED"
    NOTIFICATION_CREATE_INVALID_TYPE = "ERR.CORE.NOTIFICATION.CREATE.INVALID_TYPE"
    NOTIFICATION_CREATE_INVALID_CONTACT = "ERR.CORE.NOTIFICATION.CREATE.INVALID_CONTACT"
    NOTIFICATION_CREATE_NO_CHANNEL = "ERR.CORE.NOTIFICATION.CREATE.NO_CHANNEL"
    NOTIFICATION_GET_NOT_FOUND = "ERR.CORE.NOTIFICATION.GET.NOT_FOUND"
    NOTIFICATION_LIST_FAILED = "ERR.CORE.NOTIFICATION.LIST.FAILED"
    NOTIFICATION_EMIT_FAILED = "ERR.CORE.NOTIFICATION.EMIT.FAILED"
    NOTIFICATION_MARK_READ_NOT_FOUND = "ERR.CORE.NOTIFICATION.MARK_READ.NOT_FOUND"
    NOTIFICATION_MARK_READ_FAILED = "ERR.CORE.NOTIFICATION.MARK_READ.FAILED"
    NOTIFICATION_CANCEL_NOT_FOUND = "ERR.CORE.NOTIFICATION.CANCEL.NOT_FOUND"
    NOTIFICATION_CANCEL_FAILED = "ERR.CORE.NOTIFICATION.CANCEL.FAILED"
    NOTIFICATION_CANCEL_INVALID_STATUS = "ERR.CORE.NOTIFICATION.CANCEL.INVALID_STATUS"
    NOTIFICATION_RESEND_NOT_FOUND = "ERR.CORE.NOTIFICATION.RESEND.NOT_FOUND"
    NOTIFICATION_RESEND_INVALID_STATUS = "ERR.CORE.NOTIFICATION.RESEND.INVALID_STATUS"
    NOTIFICATION_RESEND_FAILED = "ERR.CORE.NOTIFICATION.RESEND.FAILED"
    NOTIFICATION_DELIVERY_EMAIL_FAILED = "ERR.CORE.NOTIFICATION.DELIVERY.EMAIL_FAILED"
    NOTIFICATION_DELIVERY_SMS_FAILED = "ERR.CORE.NOTIFICATION.DELIVERY.SMS_FAILED"
    NOTIFICATION_DELIVERY_PUSH_FAILED = "ERR.CORE.NOTIFICATION.DELIVERY.PUSH_FAILED"

    # =========================================================================
    # ERROR_MASTER Error Codes
    # =========================================================================
    ERROR_MASTER_CREATE_FAILED = "ERR.CORE.ERROR_MASTER.CREATE.FAILED"
    ERROR_MASTER_CREATE_DUPLICATE_CODE = "ERR.CORE.ERROR_MASTER.CREATE.DUPLICATE_CODE"
    ERROR_MASTER_CREATE_INVALID_FORMAT = "ERR.CORE.ERROR_MASTER.CREATE.INVALID_FORMAT"
    ERROR_MASTER_CREATE_INVALID_MODULE = "ERR.CORE.ERROR_MASTER.CREATE.INVALID_MODULE"
    ERROR_MASTER_CREATE_INVALID_CREATOR = "ERR.CORE.ERROR_MASTER.CREATE.INVALID_CREATOR"
    ERROR_MASTER_UPDATE_NOT_FOUND = "ERR.CORE.ERROR_MASTER.UPDATE.NOT_FOUND"
    ERROR_MASTER_UPDATE_FAILED = "ERR.CORE.ERROR_MASTER.UPDATE.FAILED"
    ERROR_MASTER_UPDATE_CODE_IMMUTABLE = "ERR.CORE.ERROR_MASTER.UPDATE.CODE_IMMUTABLE"
    ERROR_MASTER_DELETE_NOT_FOUND = "ERR.CORE.ERROR_MASTER.DELETE.NOT_FOUND"
    ERROR_MASTER_DELETE_FAILED = "ERR.CORE.ERROR_MASTER.DELETE.FAILED"
    ERROR_MASTER_DELETE_IN_USE = "ERR.CORE.ERROR_MASTER.DELETE.IN_USE"
    ERROR_MASTER_GET_NOT_FOUND = "ERR.CORE.ERROR_MASTER.GET.NOT_FOUND"
    ERROR_MASTER_GET_CODE_NOT_FOUND = "ERR.CORE.ERROR_MASTER.GET.CODE_NOT_FOUND"
    ERROR_MASTER_LIST_FAILED = "ERR.CORE.ERROR_MASTER.LIST.FAILED"
    ERROR_MASTER_BULK_CREATE_PARTIAL_FAILURE = "ERR.CORE.ERROR_MASTER.BULK_CREATE.PARTIAL_FAILURE"

    # =========================================================================
    # ERROR_LOG Error Codes
    # =========================================================================
    ERROR_LOG_CREATE_FAILED = "ERR.CORE.ERROR_LOG.CREATE.FAILED"
    ERROR_LOG_CREATE_INVALID_CODE = "ERR.CORE.ERROR_LOG.CREATE.INVALID_CODE"
    ERROR_LOG_CREATE_EMPTY_MESSAGE = "ERR.CORE.ERROR_LOG.CREATE.EMPTY_MESSAGE"
    ERROR_LOG_CREATE_INVALID_SOURCE_TYPE = "ERR.CORE.ERROR_LOG.CREATE.INVALID_SOURCE_TYPE"
    ERROR_LOG_CREATE_INVALID_ENVIRONMENT = "ERR.CORE.ERROR_LOG.CREATE.INVALID_ENVIRONMENT"
    ERROR_LOG_GET_NOT_FOUND = "ERR.CORE.ERROR_LOG.GET.NOT_FOUND"
    ERROR_LOG_SEARCH_FAILED = "ERR.CORE.ERROR_LOG.SEARCH.FAILED"
    ERROR_LOG_EXPORT_FAILED = "ERR.CORE.ERROR_LOG.EXPORT.FAILED"
    ERROR_LOG_ARCHIVE_FAILED = "ERR.CORE.ERROR_LOG.ARCHIVE.FAILED"
    ERROR_LOG_ARCHIVE_MOVE_FAILED = "ERR.CORE.ERROR_LOG.ARCHIVE.MOVE_FAILED"

    # =========================================================================
    # LOG_MASTER Error Codes
    # =========================================================================
    LOG_MASTER_CREATE_FAILED = "ERR.CORE.LOG_MASTER.CREATE.FAILED"
    LOG_MASTER_CREATE_DUPLICATE_CODE = "ERR.CORE.LOG_MASTER.CREATE.DUPLICATE_CODE"
    LOG_MASTER_UPDATE_NOT_FOUND = "ERR.CORE.LOG_MASTER.UPDATE.NOT_FOUND"
    LOG_MASTER_UPDATE_FAILED = "ERR.CORE.LOG_MASTER.UPDATE.FAILED"
    LOG_MASTER_DELETE_NOT_FOUND = "ERR.CORE.LOG_MASTER.DELETE.NOT_FOUND"
    LOG_MASTER_DELETE_FAILED = "ERR.CORE.LOG_MASTER.DELETE.FAILED"
    LOG_MASTER_DELETE_IN_USE = "ERR.CORE.LOG_MASTER.DELETE.IN_USE"
    LOG_MASTER_GET_NOT_FOUND = "ERR.CORE.LOG_MASTER.GET.NOT_FOUND"
    LOG_MASTER_LIST_FAILED = "ERR.CORE.LOG_MASTER.LIST.FAILED"

    # =========================================================================
    # LOG_TRANSACTION Error Codes
    # =========================================================================
    LOG_TRANSACTION_CREATE_FAILED = "ERR.CORE.LOG_TRANSACTION.CREATE.FAILED"
    LOG_TRANSACTION_CREATE_INVALID_LOG_CODE = "ERR.CORE.LOG_TRANSACTION.CREATE.INVALID_LOG_CODE"
    LOG_TRANSACTION_CREATE_INVALID_ACTOR = "ERR.CORE.LOG_TRANSACTION.CREATE.INVALID_ACTOR"
    LOG_TRANSACTION_UPDATE_NOT_FOUND = "ERR.CORE.LOG_TRANSACTION.UPDATE.NOT_FOUND"
    LOG_TRANSACTION_UPDATE_FAILED = "ERR.CORE.LOG_TRANSACTION.UPDATE.FAILED"
    LOG_TRANSACTION_DELETE_NOT_FOUND = "ERR.CORE.LOG_TRANSACTION.DELETE.NOT_FOUND"
    LOG_TRANSACTION_DELETE_FAILED = "ERR.CORE.LOG_TRANSACTION.DELETE.FAILED"
    LOG_TRANSACTION_GET_NOT_FOUND = "ERR.CORE.LOG_TRANSACTION.GET.NOT_FOUND"
    LOG_TRANSACTION_SEARCH_FAILED = "ERR.CORE.LOG_TRANSACTION.SEARCH.FAILED"
    LOG_TRANSACTION_EXPORT_FAILED = "ERR.CORE.LOG_TRANSACTION.EXPORT.FAILED"

    # =========================================================================
    # PROMPT Error Codes
    # =========================================================================
    PROMPT_CREATE_FAILED = "ERR.CORE.PROMPT.CREATE.FAILED"
    PROMPT_CREATE_DUPLICATE = "ERR.CORE.PROMPT.CREATE.DUPLICATE"
    PROMPT_CREATE_INVALID_CREATOR = "ERR.CORE.PROMPT.CREATE.INVALID_CREATOR"
    PROMPT_UPDATE_NOT_FOUND = "ERR.CORE.PROMPT.UPDATE.NOT_FOUND"
    PROMPT_UPDATE_FAILED = "ERR.CORE.PROMPT.UPDATE.FAILED"
    PROMPT_UPDATE_DUPLICATE = "ERR.CORE.PROMPT.UPDATE.DUPLICATE"
    PROMPT_DELETE_NOT_FOUND = "ERR.CORE.PROMPT.DELETE.NOT_FOUND"
    PROMPT_DELETE_FAILED = "ERR.CORE.PROMPT.DELETE.FAILED"
    PROMPT_DELETE_IN_USE = "ERR.CORE.PROMPT.DELETE.IN_USE"
    PROMPT_GET_NOT_FOUND = "ERR.CORE.PROMPT.GET.NOT_FOUND"
    PROMPT_LIST_FAILED = "ERR.CORE.PROMPT.LIST.FAILED"
    PROMPT_RESTORE_NOT_FOUND = "ERR.CORE.PROMPT.RESTORE.NOT_FOUND"
    PROMPT_RESTORE_FAILED = "ERR.CORE.PROMPT.RESTORE.FAILED"
    PROMPT_INVALID_NAME_FORMAT = "ERR.CORE.PROMPT.INVALID_NAME_FORMAT"
    PROMPT_NOT_FOUND = "ERR.CORE.PROMPT.NOT_FOUND"
    PROMPT_INVALID_ID = "ERR.CORE.PROMPT.INVALID_ID"
    PROMPT_NAME_ALREADY_EXISTS = "ERR.CORE.PROMPT.NAME_ALREADY_EXISTS"
    PROMPT_NOT_DELETED = "ERR.CORE.PROMPT.NOT_DELETED"

    # =========================================================================
    # PROMPT_EXECUTION Error Codes
    # =========================================================================
    PROMPT_EXEC_CREATE_FAILED = "ERR.CORE.PROMPT_EXEC.CREATE.FAILED"
    PROMPT_EXEC_CREATE_INVALID_PROMPT = "ERR.CORE.PROMPT_EXEC.CREATE.INVALID_PROMPT"
    PROMPT_EXEC_CREATE_INVALID_USER = "ERR.CORE.PROMPT_EXEC.CREATE.INVALID_USER"
    PROMPT_EXEC_UPDATE_NOT_FOUND = "ERR.CORE.PROMPT_EXEC.UPDATE.NOT_FOUND"
    PROMPT_EXEC_UPDATE_FAILED = "ERR.CORE.PROMPT_EXEC.UPDATE.FAILED"
    PROMPT_EXEC_DELETE_NOT_FOUND = "ERR.CORE.PROMPT_EXEC.DELETE.NOT_FOUND"
    PROMPT_EXEC_DELETE_FAILED = "ERR.CORE.PROMPT_EXEC.DELETE.FAILED"
    PROMPT_EXEC_GET_NOT_FOUND = "ERR.CORE.PROMPT_EXEC.GET.NOT_FOUND"
    PROMPT_EXEC_LIST_FAILED = "ERR.CORE.PROMPT_EXEC.LIST.FAILED"
    PROMPT_EXEC_EXECUTE_FAILED = "ERR.CORE.PROMPT_EXEC.EXECUTE.FAILED"
    PROMPT_EXEC_EXECUTE_TIMEOUT = "ERR.CORE.PROMPT_EXEC.EXECUTE.TIMEOUT"
    PROMPT_EXEC_EXECUTE_TOKEN_LIMIT = "ERR.CORE.PROMPT_EXEC.EXECUTE.TOKEN_LIMIT"
    PROMPT_EXEC_NOT_FOUND = "ERR.CORE.PROMPT_EXEC.NOT_FOUND"
    PROMPT_EXEC_INVALID_ID = "ERR.CORE.PROMPT_EXEC.INVALID_ID"
    PROMPT_EXEC_NOT_DELETED = "ERR.CORE.PROMPT_EXEC.NOT_DELETED"

    # =========================================================================
    # APPROVAL_FLOW_MASTER Error Codes
    # =========================================================================
    APPROVAL_FLOW_CREATE_FAILED = "ERR.CORE.APPROVAL_FLOW.CREATE.FAILED"
    APPROVAL_FLOW_CREATE_INVALID_MODULE = "ERR.CORE.APPROVAL_FLOW.CREATE.INVALID_MODULE"
    APPROVAL_FLOW_CREATE_INVALID_UNIT = "ERR.CORE.APPROVAL_FLOW.CREATE.INVALID_UNIT"
    APPROVAL_FLOW_CREATE_INVALID_RANK = "ERR.CORE.APPROVAL_FLOW.CREATE.INVALID_RANK"
    APPROVAL_FLOW_UPDATE_NOT_FOUND = "ERR.CORE.APPROVAL_FLOW.UPDATE.NOT_FOUND"
    APPROVAL_FLOW_UPDATE_FAILED = "ERR.CORE.APPROVAL_FLOW.UPDATE.FAILED"
    APPROVAL_FLOW_DELETE_NOT_FOUND = "ERR.CORE.APPROVAL_FLOW.DELETE.NOT_FOUND"
    APPROVAL_FLOW_DELETE_FAILED = "ERR.CORE.APPROVAL_FLOW.DELETE.FAILED"
    APPROVAL_FLOW_GET_NOT_FOUND = "ERR.CORE.APPROVAL_FLOW.GET.NOT_FOUND"
    APPROVAL_FLOW_LIST_FAILED = "ERR.CORE.APPROVAL_FLOW.LIST.FAILED"
    APPROVAL_FLOW_NOT_FOUND = "ERR.CORE.APPROVAL_FLOW.NOT_FOUND"
    APPROVAL_FLOW_ALREADY_ACTIVE = "ERR.CORE.APPROVAL_FLOW.ALREADY_ACTIVE"
    APPROVAL_FLOW_INVALID_ID = "ERR.CORE.APPROVAL_FLOW.INVALID_ID"

    # =========================================================================
    # APPROVAL_CHAIN Error Codes
    # =========================================================================
    # CREATE operations
    APPROVAL_CHAIN_CREATE_FAILED = "ERR.CORE.APPROVAL_CHAIN.CREATE.FAILED"
    APPROVAL_CHAIN_CREATE_INVALID_MODULE = "ERR.CORE.APPROVAL_CHAIN.CREATE.INVALID_MODULE"
    APPROVAL_CHAIN_CREATE_INVALID_UNIT = "ERR.CORE.APPROVAL_CHAIN.CREATE.INVALID_UNIT"
    APPROVAL_CHAIN_CREATE_INVALID_APPROVER = "ERR.CORE.APPROVAL_CHAIN.CREATE.INVALID_APPROVER"
    APPROVAL_CHAIN_CREATE_INVALID_RANK = "ERR.CORE.APPROVAL_CHAIN.CREATE.INVALID_RANK"
    APPROVAL_CHAIN_CREATE_INVALID_DISTRICT = "ERR.CORE.APPROVAL_CHAIN.CREATE.INVALID_DISTRICT"
    APPROVAL_CHAIN_CREATE_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.CREATE.PERMISSION_DENIED"

    # UPDATE operations
    APPROVAL_CHAIN_UPDATE_NOT_FOUND = "ERR.CORE.APPROVAL_CHAIN.UPDATE.NOT_FOUND"
    APPROVAL_CHAIN_UPDATE_FAILED = "ERR.CORE.APPROVAL_CHAIN.UPDATE.FAILED"
    APPROVAL_CHAIN_UPDATE_ALREADY_DELETED = "ERR.CORE.APPROVAL_CHAIN.UPDATE.ALREADY_DELETED"
    APPROVAL_CHAIN_UPDATE_NO_FIELDS = "ERR.CORE.APPROVAL_CHAIN.UPDATE.NO_FIELDS"
    APPROVAL_CHAIN_UPDATE_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.UPDATE.PERMISSION_DENIED"
    APPROVAL_CHAIN_UPDATE_INVALID_STATUS_TRANSITION = "ERR.CORE.APPROVAL_CHAIN.UPDATE.INVALID_STATUS_TRANSITION"

    # DELETE operations
    APPROVAL_CHAIN_DELETE_NOT_FOUND = "ERR.CORE.APPROVAL_CHAIN.DELETE.NOT_FOUND"
    APPROVAL_CHAIN_DELETE_FAILED = "ERR.CORE.APPROVAL_CHAIN.DELETE.FAILED"
    APPROVAL_CHAIN_DELETE_ALREADY_DELETED = "ERR.CORE.APPROVAL_CHAIN.DELETE.ALREADY_DELETED"
    APPROVAL_CHAIN_DELETE_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.DELETE.PERMISSION_DENIED"
    APPROVAL_CHAIN_DELETE_PENDING_APPROVAL = "ERR.CORE.APPROVAL_CHAIN.DELETE.PENDING_APPROVAL"

    # GET operations
    APPROVAL_CHAIN_GET_NOT_FOUND = "ERR.CORE.APPROVAL_CHAIN.GET.NOT_FOUND"
    APPROVAL_CHAIN_GET_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.GET.PERMISSION_DENIED"

    # LIST operations
    APPROVAL_CHAIN_LIST_FAILED = "ERR.CORE.APPROVAL_CHAIN.LIST.FAILED"
    APPROVAL_CHAIN_LIST_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.LIST.PERMISSION_DENIED"

    # RESTORE operations
    APPROVAL_CHAIN_RESTORE_NOT_FOUND = "ERR.CORE.APPROVAL_CHAIN.RESTORE.NOT_FOUND"
    APPROVAL_CHAIN_RESTORE_FAILED = "ERR.CORE.APPROVAL_CHAIN.RESTORE.FAILED"
    APPROVAL_CHAIN_RESTORE_ALREADY_ACTIVE = "ERR.CORE.APPROVAL_CHAIN.RESTORE.ALREADY_ACTIVE"
    APPROVAL_CHAIN_RESTORE_PERMISSION_DENIED = "ERR.CORE.APPROVAL_CHAIN.RESTORE.PERMISSION_DENIED"

    # VALIDATION errors
    APPROVAL_CHAIN_INVALID_ID = "ERR.CORE.APPROVAL_CHAIN.INVALID_ID"
    APPROVAL_CHAIN_INVALID_MODULE_ID = "ERR.CORE.APPROVAL_CHAIN.INVALID_MODULE_ID"
    APPROVAL_CHAIN_INVALID_UNIT_ID = "ERR.CORE.APPROVAL_CHAIN.INVALID_UNIT_ID"
    APPROVAL_CHAIN_MISSING_DISTRICT_ID = "ERR.CORE.APPROVAL_CHAIN.MISSING_DISTRICT_ID"

    # WORKFLOW specific errors
    APPROVAL_CHAIN_APPROVE_NOT_AUTHORIZED = "ERR.CORE.APPROVAL_CHAIN.APPROVE.NOT_AUTHORIZED"
    APPROVAL_CHAIN_REJECT_NOT_AUTHORIZED = "ERR.CORE.APPROVAL_CHAIN.REJECT.NOT_AUTHORIZED"
    APPROVAL_CHAIN_ALREADY_COMPLETED = "ERR.CORE.APPROVAL_CHAIN.ALREADY_COMPLETED"
    APPROVAL_CHAIN_ALREADY_REJECTED = "ERR.CORE.APPROVAL_CHAIN.ALREADY_REJECTED"

    # Backward compatibility (deprecated - use specific codes above)
    APPROVAL_CHAIN_NOT_FOUND = "ERR.CORE.APPROVAL_CHAIN.GET.NOT_FOUND"
    APPROVAL_CHAIN_ALREADY_ACTIVE = "ERR.CORE.APPROVAL_CHAIN.RESTORE.ALREADY_ACTIVE"

    # =========================================================================
    # DESIGNATION Error Codes
    # =========================================================================
    DESIGNATION_CREATE_FAILED = "ERR.CORE.DESIGNATION.CREATE.FAILED"
    DESIGNATION_CREATE_DUPLICATE_NAME = "ERR.CORE.DESIGNATION.CREATE.DUPLICATE_NAME"
    DESIGNATION_CREATE_DUPLICATE_CODE = "ERR.CORE.DESIGNATION.CREATE.DUPLICATE_CODE"
    DESIGNATION_UPDATE_NOT_FOUND = "ERR.CORE.DESIGNATION.UPDATE.NOT_FOUND"
    DESIGNATION_UPDATE_FAILED = "ERR.CORE.DESIGNATION.UPDATE.FAILED"
    DESIGNATION_UPDATE_DUPLICATE_NAME = "ERR.CORE.DESIGNATION.UPDATE.DUPLICATE_NAME"
    DESIGNATION_UPDATE_DUPLICATE_CODE = "ERR.CORE.DESIGNATION.UPDATE.DUPLICATE_CODE"
    DESIGNATION_DELETE_NOT_FOUND = "ERR.CORE.DESIGNATION.DELETE.NOT_FOUND"
    DESIGNATION_DELETE_FAILED = "ERR.CORE.DESIGNATION.DELETE.FAILED"
    DESIGNATION_DELETE_IN_USE = "ERR.CORE.DESIGNATION.DELETE.IN_USE"
    DESIGNATION_GET_NOT_FOUND = "ERR.CORE.DESIGNATION.GET.NOT_FOUND"
    DESIGNATION_LIST_FAILED = "ERR.CORE.DESIGNATION.LIST.FAILED"

    # =========================================================================
    # FEEDBACK_MASTER Error Codes
    # =========================================================================
    FEEDBACK_MASTER_CREATE_FAILED = "ERR.CORE.FEEDBACK_MASTER.CREATE.FAILED"
    FEEDBACK_MASTER_CREATE_DUPLICATE_NAME = "ERR.CORE.FEEDBACK_MASTER.CREATE.DUPLICATE_NAME"
    FEEDBACK_MASTER_CREATE_DUPLICATE_CODE = "ERR.CORE.FEEDBACK_MASTER.CREATE.DUPLICATE_CODE"
    FEEDBACK_MASTER_CREATE_INVALID_MODULE = "ERR.CORE.FEEDBACK_MASTER.CREATE.INVALID_MODULE"
    FEEDBACK_MASTER_UPDATE_NOT_FOUND = "ERR.CORE.FEEDBACK_MASTER.UPDATE.NOT_FOUND"
    FEEDBACK_MASTER_UPDATE_FAILED = "ERR.CORE.FEEDBACK_MASTER.UPDATE.FAILED"
    FEEDBACK_MASTER_UPDATE_DUPLICATE_NAME = "ERR.CORE.FEEDBACK_MASTER.UPDATE.DUPLICATE_NAME"
    FEEDBACK_MASTER_DELETE_NOT_FOUND = "ERR.CORE.FEEDBACK_MASTER.DELETE.NOT_FOUND"
    FEEDBACK_MASTER_DELETE_FAILED = "ERR.CORE.FEEDBACK_MASTER.DELETE.FAILED"
    FEEDBACK_MASTER_DELETE_IN_USE = "ERR.CORE.FEEDBACK_MASTER.DELETE.IN_USE"
    FEEDBACK_MASTER_GET_NOT_FOUND = "ERR.CORE.FEEDBACK_MASTER.GET.NOT_FOUND"
    FEEDBACK_MASTER_LIST_FAILED = "ERR.CORE.FEEDBACK_MASTER.LIST.FAILED"

    # =========================================================================
    # FEEDBACK Error Codes
    # =========================================================================
    FEEDBACK_CREATE_FAILED = "ERR.CORE.FEEDBACK.CREATE.FAILED"
    FEEDBACK_CREATE_INVALID_MASTER = "ERR.CORE.FEEDBACK.CREATE.INVALID_MASTER"
    FEEDBACK_CREATE_INVALID_USER = "ERR.CORE.FEEDBACK.CREATE.INVALID_USER"
    FEEDBACK_CREATE_INVALID_COMPONENT_TYPE = "ERR.CORE.FEEDBACK.CREATE.INVALID_COMPONENT_TYPE"
    FEEDBACK_CREATE_INVALID_PROMPT = "ERR.CORE.FEEDBACK.CREATE.INVALID_PROMPT"
    FEEDBACK_UPDATE_NOT_FOUND = "ERR.CORE.FEEDBACK.UPDATE.NOT_FOUND"
    FEEDBACK_UPDATE_FAILED = "ERR.CORE.FEEDBACK.UPDATE.FAILED"
    FEEDBACK_DELETE_NOT_FOUND = "ERR.CORE.FEEDBACK.DELETE.NOT_FOUND"
    FEEDBACK_DELETE_FAILED = "ERR.CORE.FEEDBACK.DELETE.FAILED"
    FEEDBACK_GET_NOT_FOUND = "ERR.CORE.FEEDBACK.GET.NOT_FOUND"
    FEEDBACK_LIST_FAILED = "ERR.CORE.FEEDBACK.LIST.FAILED"
    FEEDBACK_RESPOND_NOT_FOUND = "ERR.CORE.FEEDBACK.RESPOND.NOT_FOUND"
    FEEDBACK_RESPOND_FAILED = "ERR.CORE.FEEDBACK.RESPOND.FAILED"

    # =========================================================================
    # FEEDBACK_DASHBOARD Error Codes
    # =========================================================================
    FEEDBACK_DASHBOARD_FETCH_FAILED = "ERR.CORE.FEEDBACK_DASHBOARD.FETCH.FAILED"
    FEEDBACK_DASHBOARD_TOP_NEGATIVE_FAILED = "ERR.CORE.FEEDBACK_DASHBOARD.TOP_NEGATIVE.FAILED"
    FEEDBACK_DASHBOARD_REPORTS_FAILED = "ERR.CORE.FEEDBACK_DASHBOARD.REPORTS.FAILED"
    FEEDBACK_DASHBOARD_INVALID_PARAMS = "ERR.CORE.FEEDBACK_DASHBOARD.INVALID_PARAMS"

    # =========================================================================
    # ONBOARDING Error Codes
    # =========================================================================
    ONBOARDING_FAILED = "ERR.CORE.ONBOARDING.FAILED"
    ONBOARDING_PERSONNEL_FAILED = "ERR.CORE.ONBOARDING.PERSONNEL.FAILED"
    ONBOARDING_ROLE_MAPPING_FAILED = "ERR.CORE.ONBOARDING.ROLE_MAPPING.FAILED"
    ONBOARDING_VALIDATION_FAILED = "ERR.CORE.ONBOARDING.VALIDATION.FAILED"
    ONBOARDING_ROLLBACK_FAILED = "ERR.CORE.ONBOARDING.ROLLBACK.FAILED"
    
    # =========================================================================
    # TEST_MASTER Error Codes
    # =========================================================================
    TEST_MASTER_CREATE_FAILED = "ERR.CORE.TEST_MASTER.CREATE.FAILED"
    TEST_MASTER_CREATE_DUPLICATE_NAME = "ERR.CORE.TEST_MASTER.CREATE.DUPLICATE_NAME"
    TEST_MASTER_CREATE_DUPLICATE_CODE = "ERR.CORE.TEST_MASTER.CREATE.DUPLICATE_CODE"
    TEST_MASTER_CREATE_INVALID_MODULE = "ERR.CORE.TEST_MASTER.CREATE.INVALID_MODULE"
    TEST_MASTER_UPDATE_NOT_FOUND = "ERR.CORE.TEST_MASTER.UPDATE.NOT_FOUND"
    TEST_MASTER_UPDATE_FAILED = "ERR.CORE.TEST_MASTER.UPDATE.FAILED"
    TEST_MASTER_UPDATE_DUPLICATE_NAME = "ERR.CORE.TEST_MASTER.UPDATE.DUPLICATE_NAME"
    TEST_MASTER_DELETE_NOT_FOUND = "ERR.CORE.TEST_MASTER.DELETE.NOT_FOUND"
    TEST_MASTER_DELETE_FAILED = "ERR.CORE.TEST_MASTER.DELETE.FAILED"
    TEST_MASTER_DELETE_IN_USE = "ERR.CORE.TEST_MASTER.DELETE.IN_USE"
    TEST_MASTER_GET_NOT_FOUND = "ERR.CORE.TEST_MASTER.GET.NOT_FOUND"
    TEST_MASTER_LIST_FAILED = "ERR.CORE.TEST_MASTER.LIST.FAILED"
    TEST_MASTER_RESTORE_NOT_FOUND = "ERR.CORE.TEST_MASTER.RESTORE.NOT_FOUND"
    TEST_MASTER_RESTORE_FAILED = "ERR.CORE.TEST_MASTER.RESTORE.FAILED"

    # =========================================================================
    # TEST_EXECUTION Error Codes
    # =========================================================================
    TEST_EXEC_CREATE_FAILED = "ERR.CORE.TEST_EXEC.CREATE.FAILED"
    TEST_EXEC_CREATE_INVALID_TEST = "ERR.CORE.TEST_EXEC.CREATE.INVALID_TEST"
    TEST_EXEC_CREATE_INVALID_USER = "ERR.CORE.TEST_EXEC.CREATE.INVALID_USER"
    TEST_EXEC_UPDATE_NOT_FOUND = "ERR.CORE.TEST_EXEC.UPDATE.NOT_FOUND"
    TEST_EXEC_UPDATE_FAILED = "ERR.CORE.TEST_EXEC.UPDATE.FAILED"
    TEST_EXEC_DELETE_NOT_FOUND = "ERR.CORE.TEST_EXEC.DELETE.NOT_FOUND"
    TEST_EXEC_DELETE_FAILED = "ERR.CORE.TEST_EXEC.DELETE.FAILED"
    TEST_EXEC_GET_NOT_FOUND = "ERR.CORE.TEST_EXEC.GET.NOT_FOUND"
    TEST_EXEC_LIST_FAILED = "ERR.CORE.TEST_EXEC.LIST.FAILED"
    TEST_EXEC_EXECUTE_FAILED = "ERR.CORE.TEST_EXEC.EXECUTE.FAILED"
    TEST_EXEC_EXECUTE_TIMEOUT = "ERR.CORE.TEST_EXEC.EXECUTE.TIMEOUT"

    # =========================================================================
    # GENERIC/COMMON Error Codes
    # =========================================================================
    INVALID_ACTION = "ERR.CORE.INVALID_ACTION"
    PLACEHOLDER_INVALID = "ERR.CORE.PLACEHOLDER.INVALID"

    # =========================================================================
    # VALIDATION Error Codes (Pydantic/Request Validation)
    # =========================================================================
    VALIDATION_REQUEST_FAILED = "ERR.CORE.VALIDATION.REQUEST.FAILED"
    VALIDATION_RESPONSE_FAILED = "ERR.CORE.VALIDATION.RESPONSE.FAILED"

    # =========================================================================
    # THIRD_PARTY_API Error Codes
    # =========================================================================
    THIRD_PARTY_API_EXECUTE_FAILED = "ERR.CORE.THIRD_PARTY_API.EXECUTE.FAILED"
    THIRD_PARTY_API_EXECUTE_TIMEOUT = "ERR.CORE.THIRD_PARTY_API.EXECUTE.TIMEOUT"
    THIRD_PARTY_API_EXECUTE_CONNECTION_ERROR = "ERR.CORE.THIRD_PARTY_API.EXECUTE.CONNECTION_ERROR"
    THIRD_PARTY_API_BULK_EXECUTE_FAILED = "ERR.CORE.THIRD_PARTY_API.BULK_EXECUTE.FAILED"
    THIRD_PARTY_API_INVALID_URL = "ERR.CORE.THIRD_PARTY_API.INVALID_URL"
    THIRD_PARTY_API_INVALID_METHOD = "ERR.CORE.THIRD_PARTY_API.INVALID_METHOD"
