"""
Centralized Job Names Configuration
All job names used for RBAC permission checks across the application.
Import from here instead of defining JOB_NAME in individual router files.
"""


class Jobs:
    """Job names for RBAC permission checks"""

    # Master Data Jobs
    DEPARTMENTS = "DEPARTMENTS"
    DESIGNATION_MASTER = "DESIGNATION MASTER"
    DISTRICT = "DISTRICT"
    MANDALS = "MANDALS"
    RANK = "RANK"
    UNIT_TYPE = "UNIT_TYPE"

    # Core Jobs
    PERSONNEL_MASTER = "PERSONNEL"
    UNITS = "UNITS"
    UNIT_VILLAGES = "UNIT_VILLAGES"

    # Auth & RBAC Jobs
    ROLES = "ROLES"
    PERMISSIONS = "PERMISSIONS"
    PERMISSION_MAPPINGS = "PERMISSION_MAPPINGS"
    USER_ROLE_PERMISSIONS = "USER_ROLE_PERMISSIONS"
    JOBS = "JOBS"

    # Module Jobs
    MODULES = "MODULES"
    MODULE_HIERARCHY = "MODULE_HIERARCHY"
    MODULE_JOB_MAPPINGS = "MODULE_JOB_MAPPINGS"

    # Approval Jobs
    APPROVAL_FLOW_MASTER = "APPROVAL_FLOW_MASTER"
    APPROVAL_CHAIN = "APPROVAL_CHAIN"

    # Prompt Jobs
    PROMPT_MASTER = "PROMPT_TABLE"
    PROMPT_EXECUTIONS = "PROMPT_EXECUTIONS"

    # Logging Jobs
    ERROR_MASTER = "ERROR_MASTER"
    ERROR_LOGS = "ERROR_LOGS"
    LOG_MASTER = "LOG_MASTER"
    LOG_TRANSACTION = "LOG_TRANSACTION"

    # Value Sets
    VALUE_SETS = "VALUE_SETS"

    # Feedback Jobs
    FEEDBACK_MASTER = "FEEDBACK MASTER"
    FEEDBACKS = "FEEDBACKS"

    # Test Jobs
    TEST_MASTER = "TEST MASTER"
    TEST_EXECUTIONS = "TEST EXECUTIONS"

    # Organizational Structure
    ORG_STRUCTURE = "ORG_STRUCTURE"

    # Third Party API
    THIRD_PARTY_API = "THIRD_PARTY_API"


# Export as module-level constants for convenience
DEPARTMENTS = Jobs.DEPARTMENTS
DESIGNATION_MASTER = Jobs.DESIGNATION_MASTER
DISTRICT = Jobs.DISTRICT
MANDALS = Jobs.MANDALS
RANK = Jobs.RANK
UNIT_TYPE = Jobs.UNIT_TYPE
PERSONNEL_MASTER = Jobs.PERSONNEL_MASTER
UNITS = Jobs.UNITS
UNIT_VILLAGES = Jobs.UNIT_VILLAGES
ROLES = Jobs.ROLES
PERMISSIONS = Jobs.PERMISSIONS
PERMISSION_MAPPINGS = Jobs.PERMISSION_MAPPINGS
USER_ROLE_PERMISSIONS = Jobs.USER_ROLE_PERMISSIONS
JOBS = Jobs.JOBS
MODULES = Jobs.MODULES
MODULE_HIERARCHY = Jobs.MODULE_HIERARCHY
MODULE_JOB_MAPPINGS = Jobs.MODULE_JOB_MAPPINGS
APPROVAL_FLOW_MASTER = Jobs.APPROVAL_FLOW_MASTER
APPROVAL_CHAIN = Jobs.APPROVAL_CHAIN
PROMPT_MASTER = Jobs.PROMPT_MASTER
PROMPT_EXECUTIONS = Jobs.PROMPT_EXECUTIONS
ERROR_MASTER = Jobs.ERROR_MASTER
ERROR_LOGS = Jobs.ERROR_LOGS
LOG_MASTER = Jobs.LOG_MASTER
LOG_TRANSACTION = Jobs.LOG_TRANSACTION
VALUE_SETS = Jobs.VALUE_SETS
FEEDBACK_MASTER = Jobs.FEEDBACK_MASTER
FEEDBACKS = Jobs.FEEDBACKS
TEST_MASTER = Jobs.TEST_MASTER
TEST_EXECUTIONS = Jobs.TEST_EXECUTIONS
ORG_STRUCTURE = Jobs.ORG_STRUCTURE
THIRD_PARTY_API = Jobs.THIRD_PARTY_API
