"""
Department Collection Model
Collection: department_master
Purpose: Master data for departments
"""

COLLECTION_NAME = "department_master"


class DepartmentModel:
    """
    Document structure for department collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a department document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # Department name (required, max 255 chars)
            "cctnsDepartmentCd": "string",  # CCTNS Department Code (optional, max 50 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }