"""
Designation Master Collection Model
Collection: designation_master
Purpose: Master data for designations
"""

COLLECTION_NAME = "designation_master"


class DesignationMasterModel:
    """
    Document structure for designation_master collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a designation_master document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # Designation name (required, min 2 alphabets, allows alphabets + -_().)
            "designationCd": "string",  # Designation code (required, alphanumeric only, max 200 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required, from token)
            "createdAt": "datetime",  # Creation timestamp (required)
            "createdIp": "string",  # IP address of creator (optional)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional, from token)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "updatedIp": "string",  # IP address of updater (optional)
            "isActive": "boolean",  # Active flag (default: true)
            "isDelete": "boolean"  # Soft delete flag (default: false)
        }

    @staticmethod
    def indexes():
        """
        Returns the indexes for the collection
        """
        return [
            {"keys": [("name", 1)], "unique": True, "partialFilterExpression": {"isDelete": False}},
            {"keys": [("designationCd", 1)], "unique": True, "partialFilterExpression": {"isDelete": False}},
            {"keys": [("isDelete", 1)]},
            {"keys": [("isActive", 1)]},
            {"keys": [("createdAt", -1)]}
        ]
