"""
District Collection Model
Collection: district_master
Purpose: Master data for districts
"""

COLLECTION_NAME = "district_master"


class DistrictModel:
    """
    Document structure for district collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a district document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # District name (required, max 100 chars)
            "cctnsDistrictCd": "string",  # CCTNS District Code (optional, max 50 chars)
            "stateName": "string",  # State name (optional, max 100 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }