"""
Mandal Collection Model
Collection: mandal_master
Purpose: Master data for mandals (sub-districts)
"""

COLLECTION_NAME = "mandal_master"


class MandalModel:
    """
    Document structure for mandal collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a mandal document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "districtId": "ObjectId",  # FK: district._id (required)
            "mandalName": "string",  # Mandal name (required, max 255 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }

