"""
Prompt Table Collection Model
Collection: prompt_master
Purpose: Catalog of prompts used within the system, detailing their types, functionalities,
         objectives, and task-specific configurations including variable definitions in JSON format
"""

COLLECTION_NAME = "prompt_master"


class PromptModel:
    """
    Document structure for promptTable collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a promptTable document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB

            # Prompt identification and metadata
            "type": "string",  # Prompt type/category (max 200 chars, nullable)
            "name": "string",  # Prompt name - unique within type (max 200 chars, nullable)
            "iconPath": "string",  # Icon asset path (max 500 chars, nullable)
            "tech": "string",  # Technology/framework used (max 200 chars, nullable)

            # Role definitions
            "aiRole": "string",  # AI's purpose/behavior (max 200 chars, nullable)
            "systemRole": "string",  # System's expected actions (max 500 chars, nullable)

            # Task configuration
            "objective": "string",  # Main goal of the prompt (max 1000 chars, nullable)
            "taskInstructions": "string",  # Task execution steps (max 2000 chars, nullable)
            "taskInput": "string",  # Required inputs/parameters (max 1000 chars, nullable)
            "taskOutputFormat": "string",  # Expected output structure (max 1000 chars, nullable)
            "taskExample": "object",  # Sample input-output scenario in JSON format (nullable)

            # LLM configuration
            "llm": "string",  # LLM model identifier (max 100 chars, nullable)
            "settingsJson": "object",  # Runtime variables and parameters (JSON, nullable)

            # Audit fields
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (nullable)
            "updatedAt": "datetime",  # Last update timestamp (nullable)
            "isDeleted": "boolean",  # Soft delete flag (default: false)
        }

    @staticmethod
    def indexes():
        """
        Returns the indexes for promptTable collection
        """
        return [
            {
                "name": "uniq_name_type",
                "keys": [("name", 1), ("type", 1)],
                "unique": True
            },
            {
                "name": "idx_createDateTime_desc",
                "keys": [("createdAt", -1)],
                "unique": False
            },
            {
                "name": "idx_updatedDateTime_desc",
                "keys": [("updatedAt", -1)],
                "unique": False
            }
        ]

    @staticmethod
    def constraints():
        """
        Returns the business constraints for promptTable collection
        """
        return {
            "unique_name_per_type": "name must be unique within a given type",
            "created_by_fk": "createdBy must reference a valid document in the personnel collection",
            "updated_by_fk": "updatedBy must reference a valid document in the personnel collection (when present)",
            "settings_json_format": "settingsJson must be a valid JSON object (when present)"
        }