"""
PromptExecution Table Collection Model
Collection: prompt_execution
Purpose: To record and analyze the execution of prompts, capturing details about the construction,
         performance, user interaction, and feedback, facilitating continuous improvement and
         user experience optimization.
"""

COLLECTION_NAME = "prompt_execution"


class PromptExecutionModel:
    """
    Document structure for promptExecution collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a promptExecution document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB (Primary Key)

            # Foreign key references
            "promptId": "ObjectId",  # FK: promptTable._id (required)
            "userId": "ObjectId",  # FK: personnel._id (required)

            # Execution metadata
            "executionDateTime": "datetime",  # Timestamp when prompt was executed (required)

            # Prompt construction and execution details
            "promptConstructionRecord": "string",  # Construction process/methodology (nullable)
            "finalPrompt": "string",  # Final prompt text executed (nullable)
            "promptOutput": "string",  # Output generated from execution (nullable)

            # Token and cost tracking
            "inputTokenCount": "int",  # Number of input tokens (nullable)
            "outputTokenCount": "int",  # Number of output tokens (nullable)
            "cost": "float",  # Execution cost (nullable)
            "executionTime": "float",  # Execution time in seconds (nullable)

            # Revision tracking
            "originalWorkId": "ObjectId",  # FK: promptExecution._id (nullable, for revisions)
            "revision": "int",  # Revision number (nullable)

            # Feedback reference
            "feedbackId": "ObjectId",  # FK: feedback._id (nullable)

            # Audit fields (transaction table - no isActive)
            "isDelete": "boolean",  # Soft delete flag (default: false)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "createdIp": "string",  # IP address from which record was created (nullable)
            "updatedBy": "ObjectId",  # FK: personnel._id (nullable)
            "updatedAt": "datetime",  # Last update timestamp (nullable)
            "updatedIp": "string",  # IP address from which record was last updated (nullable)
        }

    @staticmethod
    def indexes():
        """
        Returns the indexes for promptExecution collection
        """
        return [
            {
                "name": "idx_promptId",
                "keys": [("promptId", 1)],
                "unique": False
            },
            {
                "name": "idx_userId",
                "keys": [("userId", 1)],
                "unique": False
            },
            {
                "name": "idx_executionDateTime_desc",
                "keys": [("executionDateTime", -1)],
                "unique": False
            },
            {
                "name": "idx_feedbackId",
                "keys": [("feedbackId", 1)],
                "unique": False
            },
            {
                "name": "idx_originalWorkId",
                "keys": [("originalWorkId", 1)],
                "unique": False
            },
            {
                "name": "idx_createdAt_desc",
                "keys": [("createdAt", -1)],
                "unique": False
            },
            {
                "name": "idx_cost",
                "keys": [("cost", 1)],
                "unique": False
            }
        ]

    @staticmethod
    def constraints():
        """
        Returns the business constraints for promptExecution collection
        """
        return {
            "promptId_fk": "promptId must reference a valid document in the promptTable collection",
            "userId_fk": "userId must reference a valid document in the personnel collection",
            "feedbackId_fk": "feedbackId must reference a valid document in the feedback collection (when present)",
            "originalWorkId_fk": "originalWorkId must reference a valid document in the promptExecution collection (when present)",
            "createdBy_fk": "createdBy must reference a valid document in the personnel collection",
            "updatedBy_fk": "updatedBy must reference a valid document in the personnel collection (when present)",
            "token_counts": "inputTokenCount and outputTokenCount must be non-negative integers (when present)",
            "cost_positive": "cost must be a non-negative number (when present)",
            "execution_time_positive": "executionTime must be a non-negative number (when present)",
            "revision_positive": "revision must be a non-negative integer (when present)"
        }