"""
Rank Master Collection Model
Collection: rank_master
Purpose: Master data for police ranks
"""

COLLECTION_NAME = "rank_master"


class RankMasterModel:
    """
    Document structure for rankMaster collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a rankMaster document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # Rank name (required, max 100 chars)
            "cctnsRankCd": "string",  # CCTNS Rank Code (optional, max 50 chars)
            "shortCode": "string",  # Short code for rank (optional, max 20 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }