"""
Title Master Collection Model
Collection: titleMaster
Purpose: Master data for titles (Mr, Ms, Dr, etc.)
"""

COLLECTION_NAME = "titleMaster"


class TitleMasterModel:
    """
    Document structure for titleMaster collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a titleMaster document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # Title name (required, max 50 chars)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }