"""
Unit Type Collection Model
Collection: unit_type_master
Purpose: Master data for unit types
"""

COLLECTION_NAME = "unit_type_master"


class UnitTypeModel:
    """
    Document structure for unitType collection
    """
    collection_name = COLLECTION_NAME

    @staticmethod
    def document_structure():
        """
        Returns the structure of a unitType document
        """
        return {
            "_id": "ObjectId",  # Auto-generated by MongoDB
            "name": "string",  # Unit type name (required, max 100 chars)
            "departmentId": "ObjectId",  # FK: department._id (optional)
            "createdBy": "ObjectId",  # FK: personnel._id (required)
            "createdAt": "datetime",  # Creation timestamp (required)
            "updatedBy": "ObjectId",  # FK: personnel._id (optional)
            "updatedAt": "datetime",  # Last update timestamp (optional)
            "isDeleted": "boolean"  # Soft delete flag (default: false)
        }